RPC_URL = "https://api.mainnet-beta.solana.com"
WALLET_PRIVATE_KEY = "PASTE_YOUR_PRIVATE_KEY_HERE"
PUBLIC_KEY = "CAvb2VDfQVevxzgScmbRDeZ291iCN43eERZwhP7ndM3h"
BIRDEYE_API_KEY = "PASTE_YOUR_BIRDEYE_API_KEY_HERE"
